USE BankApp

GO

CREATE TABLE USERS(
LOGIN VARCHAR(50) PRIMARY KEY NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
NOM_USER VARCHAR(50) NOT NULL ,
PRENOM_USER VARCHAR(50) NOT NULL ,
MAIL_USER VARCHAR(50) NOT NULL ,
TELEPHONE_USER NCHAR(10)  NOT NULL,
ID_BANQUE INT NOT NULL)

CREATE TABLE CLIENTS(
ID_CLIENT INT IDENTITY PRIMARY KEY NOT NULL ,
NOM_CLIENT VARCHAR(50) NOT NULL ,
PRENOM_CLIENT VARCHAR(50) NOT NULL ,
MAIL_CLIENT VARCHAR(50) NOT NULL ,
TELEPHONE_CLIENT NCHAR(10)  NOT NULL)

CREATE TABLE COMPTE(
NUMERO_COMPTE INT PRIMARY KEY NOT NULL ,
SOLDE FLOAT NOT NULL,
ID_TYPE_COMPTE INT NOT NULL,
ID_OPERATION INT NOT NULL)

CREATE TABLE CLIENT_COMPTE(
NUMERO_COMPTE INT PRIMARY KEY NOT NULL,
ID_CLIENT INT NOT NULL)

CREATE TABLE TYPECOMPTE(
ID_TYPE_COMPTE INT PRIMARY KEY IDENTITY NOT NULL ,
NOM_TYPE_COMPTE VARCHAR(50) NOT NULL,
TAUX_INTERET FLOAT NOT NULL)

CREATE TABLE OPERATIONS(
ID_OPERATION INT PRIMARY KEY NOT NULL ,
TYPE_OPERATION VARCHAR(50) NOT NULL,
DATE DATETIME NOT NULL)

CREATE TABLE BANQUES(
ID_BANQUE INT IDENTITY PRIMARY KEY NOT NULL ,
NOM_BANQUE VARCHAR(50) NOT NULL ,
ADRESSE_BANQUE VARCHAR(50) NOT NULL,
TELEPHONE_BANQUE NCHAR(10) NOT NULL)

CREATE TABLE BANQUE_CLIENT(
ID_BANQUE INT PRIMARY KEY NOT NULL,
ID_CLIENT INT NOT NULL)

ALTER TABLE USERS ADD CONSTRAINT
FK_USERS FOREIGN KEY(ID_BANQUE) REFERENCES dbo.BANQUES(ID_BANQUE)

ALTER TABLE dbo.COMPTE ADD CONSTRAINT
FK_COMPTE1 FOREIGN KEY(ID_TYPE_COMPTE) REFERENCES dbo.TYPECOMPTE(ID_TYPE_COMPTE)

ALTER TABLE dbo.COMPTE ADD CONSTRAINT
FK_COMPTE2 FOREIGN KEY(ID_OPERATION) REFERENCES dbo.OPERATIONS(ID_OPERATION)

ALTER TABLE dbo.CLIENT_COMPTE ADD CONSTRAINT
FK_CLIENT_COMPTE1 FOREIGN KEY(NUMERO_COMPTE) REFERENCES dbo.COMPTE(NUMERO_COMPTE)

ALTER TABLE dbo.CLIENT_COMPTE ADD CONSTRAINT
FK_CLIENT_COMPTE2 FOREIGN KEY(ID_CLIENT) REFERENCES dbo.CLIENTS(ID_CLIENT)

ALTER TABLE BANQUE_CLIENT ADD CONSTRAINT
FK_BANQUE_CLIENT1 FOREIGN KEY(ID_BANQUE) REFERENCES BANQUES(ID_BANQUE)

ALTER TABLE BANQUE_CLIENT ADD CONSTRAINT
FK_BANQUE_CLIENT2 FOREIGN KEY(ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT)