//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANK_WPF.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANQUES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANQUES()
        {
            this.USERS = new HashSet<USERS>();
        }
    
        public int ID_BANQUE { get; set; }
        public string NOM_BANQUE { get; set; }
        public string ADRESSE_BANQUE { get; set; }
        public string TELEPHONE_BANQUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS> USERS { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
    }
}
