//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANK_WPF.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.BANQUES = new HashSet<BANQUES>();
            this.COMPTE = new HashSet<COMPTE>();
        }
    
        public int ID_CLIENT { get; set; }
        public string NOM_CLIENT { get; set; }
        public string PRENOM_CLIENT { get; set; }
        public string MAIL_CLIENT { get; set; }
        public string TELEPHONE_CLIENT { get; set; }
        public System.DateTime DATE_NAISS_CLIENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANQUES> BANQUES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPTE> COMPTE { get; set; }
    }
}
