//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANK_WPF.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string NOM_USER { get; set; }
        public string PRENOM_USER { get; set; }
        public string MAIL_USER { get; set; }
        public string TELEPHONE_USER { get; set; }
        public int ID_BANQUE { get; set; }
    
        public virtual BANQUES BANQUES { get; set; }
    }
}
